# Generated by Django 5.1.7 on 2025-03-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fon Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('creation_date', models.DateField(verbose_name='Oluşturma Tarihi')),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yönetim Ücreti (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('risk_level', models.CharField(choices=[('low', 'Düşük Risk'), ('medium', 'Orta Risk'), ('high', 'Yüksek Risk')], default='medium', max_length=10, verbose_name='Risk Seviyesi')),
                ('target_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hedef Getiri (%)')),
                ('initial_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Başlangıç Değeri')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Güncel Değer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Zamanı')),
                ('total_shares', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Pay Adedi')),
            ],
            options={
                'verbose_name': 'Fon',
                'verbose_name_plural': 'Fonlar',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Hisse Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Şirket Adı')),
                ('icon', models.URLField(blank=True, max_length=255, null=True, verbose_name='Hisse İkonu URL')),
            ],
            options={
                'verbose_name': 'Hisse Senedi',
                'verbose_name_plural': 'Hisse Senetleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='T.C. Kimlik No / Vergi No')),
                ('risk_profile', models.CharField(choices=[('low', 'Düşük Risk'), ('medium', 'Orta Risk'), ('high', 'Yüksek Risk')], default='medium', max_length=20, verbose_name='Risk Profili')),
                ('investment_goal', models.TextField(blank=True, null=True, verbose_name='Yatırım Hedefi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Yatırım Tutarı')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Yatırım Başlangıç Tarihi')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Yatırımcının aylık düzenli yatırım tutarı', max_digits=10, verbose_name='Aylık Katkı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yatırımcı',
                'verbose_name_plural': 'Yatırımcılar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yatırım Tutarı')),
                ('date', models.DateField(verbose_name='Yatırım Tarihi')),
                ('investment_type', models.CharField(choices=[('initial', 'İlk Yatırım'), ('additional', 'Ek Yatırım'), ('monthly', 'Düzenli Aylık Yatırım'), ('dividend', 'Temettü Yeniden Yatırımı'), ('bonus', 'Bonus/Prim')], default='additional', max_length=20, verbose_name='Yatırım Tipi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='hisse_takip.investor', verbose_name='Yatırımcı')),
            ],
            options={
                'verbose_name': 'Yatırım Girişi',
                'verbose_name_plural': 'Yatırım Girişleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Portföy Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('target_return', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hedef Getiri (%)')),
                ('risk_level', models.CharField(choices=[('low', 'Düşük Risk'), ('medium', 'Orta Risk'), ('high', 'Yüksek Risk')], default='medium', max_length=10, verbose_name='Risk Seviyesi')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='hisse_takip.fund', verbose_name='Bağlı Fon')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='hisse_takip.investor', verbose_name='Yatırımcı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Portföy',
                'verbose_name_plural': 'Portföyler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('above', 'Üzerinde'), ('below', 'Altında'), ('percent_change', 'Yüzde Değişim')], max_length=15, verbose_name='Koşul Tipi')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Eşik Değeri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Tetiklenme Tarihi')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Bildirim Gönderildi mi?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hisse_takip.stock', verbose_name='Hisse Senedi')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarmlar',
                'ordering': ['user', 'stock__code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Alım'), ('sell', 'Satım'), ('dividend', 'Temettü'), ('split', 'Bölünme'), ('merger', 'Birleşme'), ('rights', 'Bedelsiz/Rüçhan')], max_length=10, verbose_name='İşlem Tipi')),
                ('date', models.DateTimeField(verbose_name='İşlem Tarihi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Miktar')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Komisyon')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vergi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='hisse_takip.investor', verbose_name='Yatırımcı')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hisse_takip.portfolio', verbose_name='Portföy')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='hisse_takip.stock', verbose_name='Hisse Senedi')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Liste Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İzleme Listesi',
                'verbose_name_plural': 'İzleme Listeleri',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FundShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_count', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Pay Adedi')),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yatırım Tutarı')),
                ('entry_date', models.DateField(verbose_name='Giriş Tarihi')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='hisse_takip.fund', verbose_name='Fon')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_shares', to='hisse_takip.investor', verbose_name='Yatırımcı')),
            ],
            options={
                'verbose_name': 'Fon Payı',
                'verbose_name_plural': 'Fon Payları',
                'unique_together': {('fund', 'investor')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Toplam Değer')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Toplam Maliyet')),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kar/Zarar')),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Kar/Zarar Yüzdesi')),
                ('benchmark_comparison', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kıyaslama Farkı')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='hisse_takip.portfolio', verbose_name='Portföy')),
            ],
            options={
                'verbose_name': 'Portföy Anlık Görüntüsü',
                'verbose_name_plural': 'Portföy Anlık Görüntüleri',
                'ordering': ['portfolio', '-date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Değişim (%)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İşlem Hacmi')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Günlük En Düşük')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Günlük En Yüksek')),
                ('update_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Güncelleme Saati')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hisse_takip.stock', verbose_name='Hisse')),
            ],
            options={
                'verbose_name': 'Fiyat Verisi',
                'verbose_name_plural': 'Fiyat Verileri',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='hisse_takip_timesta_cdfb00_idx'), models.Index(fields=['stock', 'timestamp'], name='hisse_takip_stock_i_14a11f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Miktar')),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ortalama Maliyet')),
                ('open_date', models.DateField(verbose_name='Açılış Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('is_open', models.BooleanField(default=True, verbose_name='Açık Pozisyon mu?')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hedef Fiyat')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zarar Kesme')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hisse_takip.portfolio', verbose_name='Portföy')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='hisse_takip.stock', verbose_name='Hisse Senedi')),
            ],
            options={
                'verbose_name': 'Pozisyon',
                'verbose_name_plural': 'Pozisyonlar',
                'ordering': ['portfolio', 'stock__code'],
                'unique_together': {('portfolio', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='WatchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hedef Fiyat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='hisse_takip.stock', verbose_name='Hisse Senedi')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hisse_takip.watchlist', verbose_name='İzleme Listesi')),
            ],
            options={
                'verbose_name': 'İzleme Öğesi',
                'verbose_name_plural': 'İzleme Öğeleri',
                'ordering': ['watchlist', 'stock__code'],
                'unique_together': {('watchlist', 'stock')},
            },
        ),
    ]
