# Generated by Django 5.1.7 on 2025-03-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisse_takip', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
